# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  N = 3
  controller_public_ips = []

  (1..N).each do |i|
    config.vm.define "controller#{i}" do |node|
      node.vm.hostname = "controller#{i}"
      node.vm.network "private_network", ip: "192.168.56.10#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end

      controller_public_ips << "192.168.56.10#{i}"
  end
end

  config.vm.define "loadbalancer" do |lb|

    lb.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1 
      end

    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip: "192.168.56.120"
  end

  # Generate Ansible inventory file on the host machine
  File.open("../ansible/inventory.ini", "w") do |file|
    file.write("[controllers]\n")
    (1..N).each do |i|
      private_key_path = File.expand_path(".vagrant/machines/controller#{i}/virtualbox/private_key", __dir__)
      file.write("controller#{i} ansible_host=192.168.56.10#{i} ansible_user=vagrant ansible_ssh_private_key_file=#{private_key_path}\n")
    end

    file.write("\n[loadbalancers]\n")
    lb_private_key_path = File.expand_path(".vagrant/machines/loadbalancer/virtualbox/private_key", __dir__)
    file.write("loadbalancer ansible_host=192.168.56.120 ansible_user=vagrant ansible_ssh_private_key_file=#{lb_private_key_path}\n")
  end

  # Pass Kubernetes lb IP to Ansible, replace
  File.open("../ansible/group_vars/all.yaml", "w") do |file|
    file.write("kubernetes_lb_ip: 192.168.56.120")
  end
end
