---
- name: Install HAproxy
  apt:
    name: haproxy
    state: present

- name: Configure HAproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Add controllers to hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  with_items:
    - "{{ hostvars['controller1']['ansible_host'] }} controller1"
    - "{{ hostvars['controller2']['ansible_host'] }} controller2"
    - "{{ hostvars['controller3']['ansible_host'] }} controller3"

- name: Start HAproxy
  service:
    name: haproxy 
    state: restarted
    enabled: true

