---
- name: Initialize nodes 
  hosts: controllers,workers
  become: yes
  vars: 
    kubeadm_version: "1.26.3-00"
    kubelet_version: "1.26.3-00"
    kubectl_version: "1.26.3-00"
  roles:
    - init_nodes
    
- name: Install containerd 
  hosts: controllers,workers 
  become: yes
  vars:
    containerd_version: "1.7.0"
    runc_version: "1.1.4"
    cni_plugins_version: "1.2.0"
  roles: 
    - containerd

- name: Configure HAproxy loadbalancer
  hosts: loadbalancer
  become: yes
  roles:
    - loadbalancer

- name: Initiate control plane 
  hosts: controllers
  become: yes 
  vars:
    target_controller: controller1
  roles: 
    - k8s_control_plane

- name: Join workers
  hosts: controllers,workers
  become: yes
  roles: 
    - k8s_worker_nodes

