---
- name: Initialize nodes 
  hosts: controllers #,workers
  become: yes
  roles:
    - init_nodes
    
- name: Install containerd 
  hosts: controllers #,workers 
  become: yes
  vars:
    containerd_version: "1.7.0"
    runc_version: "1.1.4"
    cni_plugins_version: "1.2.0"
  roles: 
    - containerd

- name: Configure NGINX loadbalancer
  hosts: loadbalancer
  become: yes
  roles:
    - loadbalancer

- name: Initiate control plane 
  hosts: controllers
  become: yes 
  vars:
    target_controller: controller1
  roles: 
    - k8s_control_plane
